# This is a basic workflow to help you get started with Actions

name: CI-My_Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Print files using vars  
      run: |
        echo "Modified files - $modified"
        for modfile in ${{ modified }}
        do
          echo ${modfile}
        done

        echo "Newly added files - $added"
#        for addfile in ${{ added }}
#        do
#          echo ${addfile}
#        done
      env:
        modified: ${{ steps.files.outputs.modified }}
        added: ${{ steps.files.outputs.added }}


#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

#      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: write-host Hello, world!

#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          write-host Add other actions to build,
#          write-host test, and deploy your project.
          
#      # Exports a text file
#      - name: Exports a text file
#        run: |
#          Write-output "This a Github actions test. Now I'm making some changes in this text." | out-file output.txt
#          Write-output "Output 2" | out-file output2.txt
          
#      - name: Uploads output file
#        uses: actions/upload-artifact@v3
#        with:
#          name: upload-output-file
#          path: output.txt
          
#      - name: Test Git
#        env:
#          git: C:\Program Files\Git\bin\git.exe
#        run: |
#          git config --global user.email "uzair_ansari3@hotmail.com"
#          git config --global user.name "Uzair Ansari"
#          git add output2.txt
#          git commit -m "add output2.txt"
#          git push          
        
#  Download_artifact:
#    strategy:
#      matrix:
#        os: [windows-latest, ubuntu-latest, macos-latest]
#    runs-on: ${{ matrix.os }}
#    needs: build
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Downloads Git repo
#        uses: actions/checkout@v3
      
#      - name: Download artifact file
#        uses: actions/download-artifact@v3
#        with: 
#          name: upload-output-file

#      - name: Read content of output file
#        shell: pwsh
#        run: Scripts/Workflow-test.ps1   
      
#      - name: Upload final file
#        uses: actions/upload-artifact@v3
#        with:
#          name: upload-final-file
#          path: final.txt

    
      
      
      
      
      
      
      
      
