# This is a basic workflow to help you get started with Actions

name: CI-My_Workflow_copy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: write-host Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          write-host Add other actions to build,
          write-host test, and deploy your project.
          
      # Exports a text file
      - name: Exports a text file
        run: |
          Write-output "This a Github actions test. Now I'm making some changes in this text." | out-file output.txt
          
      - name: Read content of output file job 1
        shell: pwsh
        run: |
          (Get-Item .\).fullname
          Get-ChildItem D:\ -Recurse | select FullName, LastWriteTime | ft -AutoSize -Wrap
          Scripts\Workflow-test.ps1
        
  Download_artifact:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:

      - name: Read content of output file
        shell: pwsh
        run: |
          (Get-Item .\).fullname
          Get-ChildItem D:\ -Recurse | select FullName, LastWriteTime | ft -AutoSize -Wrap
          Scripts\Workflow-test.ps1
